const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    // name of your api
    title: 'My Blog',
    description: 'This is a sample project for Blog',
    version: '1.0.0',
    tags: [
      // by default: empty Array
      {
        name: '', // Tag name
        description: '' // Tag description
      }
      // { ... }
    ]
  },
  host: 'localhost:3000'
}

const outputFile = '../utils/swagger-output.json'
// assuming your routes are located in app.js
const routes = ['../../index.js']
swaggerAutogen(outputFile, routes, doc)

// refer -https://dev.to/luizcalaca/autogenerated-documentation-api-with-openapi-and-swagger-for-nodejs-and-express-31g9
