const swaggerAutogen = require('swagger-autogen')();

const doc = {
 info: {
// name of your api
  title: 'My API',
  description: 'Description'
 },
 host: 'localhost:3000'
};

const outputFile = './swagger-output.json';
// assuming your routes are located in app.js
const routes = ['./index.js'];
swaggerAutogen(outputFile, routes, doc);


// refer -https://dev.to/luizcalaca/autogenerated-documentation-api-with-openapi-and-swagger-for-nodejs-and-express-31g9